parser: '@typescript-eslint/parser'
extends:
  - 'plugin:@typescript-eslint/recommended'
  - 'standard'
parserOptions:
  ecmaVersion: 2018
  project: ./tsconfig.json
rules:
  comma-dangle:
    - error
    - always-multiline
