services:
  npm:
    image: andrewmackrodt/nodejs-chromium
    network_mode: host
    working_dir: /app
    entrypoint:
      - /usr/local/bin/docker-entrypoint.sh
      - npm
    command: run start
    environment:
      - PUID=${UID:-}
      - GUID=${UID:-}
      - TZ=${TZ:-Europe/London}
    ports:
      - ${WEBPACK_HOST:-127.0.0.1}:${WEBPACK_PORT:-5000}:5000
    volumes:
      - config:/home/ubuntu/.config
      - npm:/home/ubuntu/.npm
      - node_modules:/home/ubuntu/node_modules
      - ./:/app

volumes:
  config:
  npm:
  node_modules:
